# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_plant_common_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='nitrogen_fixing',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
