# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_auto_20160413_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='windbreak',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
