# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_auto_20160416_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tagcolor',
            new_name='tag_color',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tagname',
            new_name='tag_name',
        ),
    ]
