# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_auto_20160416_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(blank=True, null=True)),
                ('nitrogen_fixing', models.BooleanField()),
                ('windbreak', models.BooleanField()),
                ('text', models.TextField(blank=True, null=True)),
                ('plant', models.ManyToManyField(to='plant.Plant')),
            ],
        ),
        migrations.AddField(
            model_name='zone',
            name='plant',
            field=models.ManyToManyField(to='plant.Plant'),
        ),
    ]
