# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0007_auto_20160416_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='zone',
            old_name='zone_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag_name',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='plant',
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='name', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='plants',
            field=models.ManyToManyField(to='plant.LocalPlant'),
        ),
        migrations.RemoveField(
            model_name='localplant',
            name='plant',
        ),
        migrations.AddField(
            model_name='localplant',
            name='plant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plant.Plant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='plants',
            field=models.ManyToManyField(to='plant.LocalPlant'),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='local_plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.LocalPlant'),
        ),
    ]
