# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0009_localplant_common_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='nitrogen_fixing',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='windbreak',
        ),
    ]
